variables:
  TESTING_IMAGE: framasoft/framadate-ci:php-7.2

image: ${TESTING_IMAGE}

cache:
  key: "${TESTING_IMAGE}:${CI_PROJECT_ID}"
  paths:
    - vendor/

before_script:
  - composer install -o  --no-interaction --no-progress --prefer-dist

stages:
  - test
  - deploy
  - beta
  - funky

# Run phpunit on all branches
test:
  stage: test
  script:
    - vendor/bin/phpunit --bootstrap app/tests/bootstrap.php --debug app/tests

# Run php-cs-fixer on all branches
lint:
  stage: test
  script:
    - php vendor/bin/php-cs-fixer fix --verbose --dry-run --diff

# Run doctrine migrations with MySQL
.db:migration:mysql:
  stage: test
  variables:
    APP_ENV: "test"
    MYSQL_DATABASE: "fd_test"
    MYSQL_ROOT_PASSWORD: "coucou"
    FRAMADATE_DB_DRIVER: 'pdo_mysql'
    FRAMADATE_DB_HOST: "mysql"
    FRAMADATE_DB_NAME: "${MYSQL_DATABASE}"
    FRAMADATE_DB_USER: "root"
    FRAMADATE_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  script:
    - docker-php-ext-install "${FRAMADATE_DB_DRIVER}"
    - bin/doctrine migrations:status -vvv
    - bin/doctrine migrations:migrate --no-interaction -vvv
    - bin/doctrine migrations:status -vvv

db:migration:mysql:5.6:
  extends: .db:migration:mysql
  services:
    - 'mysql:5.6'

db:migration:mysql:5.7:
  extends: .db:migration:mysql
  services:
    - 'mysql:5.7'

db:migration:mysql:8:
  extends: .db:migration:mysql
  services:
    - name: 'mysql:8'
      command: ['--default-authentication-plugin=mysql_native_password']

# Run doctrine migrations with PostgreSQL
.db:migration:postgresql:
  stage: test
  variables:
    APP_ENV: "test"
    POSTGRES_DB: "fd_test"
    POSTGRES_USER: "marmotte"
    POSTGRES_PASSWORD: "sleeping"
    FRAMADATE_DB_DRIVER: 'pdo_pgsql'
    FRAMADATE_DB_HOST: "postgres"
    FRAMADATE_DB_NAME: "${POSTGRES_DB}"
    FRAMADATE_DB_USER: "${POSTGRES_USER}"
    FRAMADATE_DB_PASSWORD: "${POSTGRES_PASSWORD}"
  script:
    - docker-php-ext-install "${FRAMADATE_DB_DRIVER}"
    - bin/doctrine migrations:status -vvv
    - bin/doctrine migrations:migrate --no-interaction -vvv
    - bin/doctrine migrations:status -vvv

db:migration:postgresql:9.6:
  extends: .db:migration:postgresql
  services:
    - 'postgres:9.6'

# Create artifacts on master
pages:
  stage: deploy
  script:
  - latesttag=$(git describe --tags)
  - git checkout ${latesttag}
  - composer install -o  --no-interaction --no-progress --prefer-dist --no-dev
  - composer dump-autoload --optimize --no-dev --classmap-authoritative
  - mkdir framadate
  - mv `ls -A | grep -v framadate` ./framadate
  - find framadate/ -type d -exec chmod 750 {} \;
  - find framadate/ -type f -exec chmod 640 {} \;
  - rm -rf framadate/.git
  - export RELEASE_ZIP="framadate-${CI_COMMIT_TAG}.zip"
  - zip -r $RELEASE_ZIP framadate
  - mkdir .public
  - cp $RELEASE_ZIP .public/latest.zip
  - mv .public public
  - if [[ -z $GITLAB_API_TOKEN ]]; then exit; fi
  - export PROJECT_API_URL="https://framagit.org/api/v4/projects/${CI_PROJECT_ID}"
  - export DESCRIPTION_URL="${PROJECT_API_URL}/repository/tags/${CI_COMMIT_TAG}"
  - export RELEASE_URL="${DESCRIPTION_URL}/release"
  - 'export HEADER="Private-Token: ${GITLAB_API_TOKEN}"'
  - export artifactUrl=$(curl -s --request POST --header "${HEADER}" --form "file=@${RELEASE_ZIP}" "${PROJECT_API_URL}/uploads" | jq -r .url)
  - export artifactAbsoluteUrl="${CI_PROJECT_URL}${artifactUrl}"
  - export description=$(curl -s --header "${HEADER}" "${DESCRIPTION_URL}" | jq .release.description | sed -e 's@"@@g')
  - if [[ $description == 'null' ]]; then export METHOD="POST"; echo -e 'You can download the release zip here:'" [${RELEASE_ZIP}](${artifactAbsoluteUrl})" > /tmp/text; fi
  - if [[ $description != 'null' ]]; then export METHOD="PUT";  echo -e "${description}\n\n"'You can download the release zip here:'" [${RELEASE_ZIP}](${artifactAbsoluteUrl})" > /tmp/text; fi
  - curl -s --request $METHOD --data-urlencode "description@/tmp/text" --header "${HEADER}" "${RELEASE_URL}"
  - curl -s --request POST --header "${HEADER}" --data name="${RELEASE_ZIP}" --data url="${artifactAbsoluteUrl}" "${PROJECT_API_URL}/releases/${CI_COMMIT_TAG}/assets/links"
  artifacts:
    paths:
    - public
  only:
    - tags
  except:
    - (beta|alpha)

# Deploy on develop
beta:
  stage: beta
  script:
  - composer install -o  --no-interaction --no-progress --prefer-dist --no-dev
  - composer dump-autoload --optimize --no-dev --classmap-authoritative
  - mkdir .public
  - cp -r * .public
  - cp -r .git .public
  - mv .public public
  - mkdir "${HOME}/.ssh"
  - chmod 700 "${HOME}/.ssh"
  - if [ ! -z ${DEPLOYEMENT_KNOWN_HOSTS+x} ]; then echo -e "${DEPLOYEMENT_KNOWN_HOSTS}" > ${HOME}/.ssh/known_hosts; fi
  - eval `ssh-agent -s`
  - if [ ! -z ${BETA_KEY+x} ]; then ssh-add <(echo "${BETA_KEY}" | base64 --decode -i); fi
  - if [ ! -z ${BETA_KEY+x} ]; then rsync -a --delete --exclude admin/.stdout.log --exclude admin/.htpasswd --exclude app/inc/config.php --exclude stats/ --exclude error/ public/ ${BETA_USER}@${DEPLOYEMENT_HOST}:../../web/; fi
  only:
    - develop

# Deploy on funky
funky:
  stage: funky
  script:
  - composer install
  - mkdir tpl_c
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - mkdir "${HOME}/.ssh"
  - chmod 700 "${HOME}/.ssh"
  - if [ ! -z ${DEPLOYEMENT_KNOWN_HOSTS+x} ]; then echo -e "${DEPLOYEMENT_KNOWN_HOSTS}" > ${HOME}/.ssh/known_hosts; fi
  - eval `ssh-agent -s`
  - if [ ! -z ${DEPLOYEMENT_KEY+x} ]; then ssh-add <(echo "${DEPLOYEMENT_KEY}" | base64 --decode -i); fi
  - if [ ! -z ${DEPLOYEMENT_KEY+x} ]; then rsync -a --delete --exclude admin/.stdout.log --exclude admin/.htpasswd --exclude app/inc/config.php --exclude stats/ --exclude error/ public/ ${DEPLOYEMENT_USER}@${DEPLOYEMENT_HOST}:../../web/; fi
  only:
    - funky
